### ISSUE TITLE
Clip, Splitter, for, split, sequences, v1.0

### ISSUE THREAD

**Issue by justinli** [antiero/dotStudio#10]
Clip, Splitter, for, split, sequences, v1.0
How to work under NukeStudio in window system?

**Comment by justinli** [comment]
File "C:\Program Files\Nuke11.0v1\pythonextensions\site-packages\hiero\core\find_plugins.py", line 42, in loadPluginsFromFolder
    module = imp.load_source( moduleName, p )
  File "C:/Users/justin.li/.nuke\Python\Startup\__init__.py", line 2, in <module>
    import csv_tag_report
  File "C:/Users/justin.li/.nuke\Python\Startup\csv_tag_report.py", line 7, in <module>
    from PySide2.QtGui import QDesktopServices
ImportError: cannot import name QDesktopServices
ERROR 01:43:51.385:Hiero(11012): Plugin C:/Users/justin.li/.nuke\Python\Startup\csv_tag_report.py could not be loaded: cannot import name QDesktopServices
Traceback (most recent call last):
  File "C:\Program Files\Nuke11.0v1\pythonextensions\site-packages\hiero\core\find_plugins.py", line 42, in loadPluginsFromFolder
    module = imp.load_source( moduleName, p )
  File "C:/Users/justin.li/.nuke\Python\Startup\csv_tag_report.py", line 7, in <module>
    from PySide2.QtGui import QDesktopServices
ImportError: cannot import name QDesktopServices
ERROR 01:43:51.641:Hiero(11012): Plugin C:/Users/justin.li/.nuke\Python\Startup\frameio_exporter\__init__.py could not be loaded: No module named QtWebKit
Traceback (most recent call last):
  File "C:\Program Files\Nuke11.0v1\pythonextensions\site-packages\hiero\core\find_plugins.py", line 53, in loadPluginsFromFolder
    module = __import__( packageName )
  File "C:/Users/justin.li/.nuke\Python\Startup\frameio_exporter\__init__.py", line 2, in <module>
    import ui
  File "C:/Users/justin.li/.nuke\Python\Startup\frameio_exporter\ui\__init__.py", line 14, in <module>
    import FnFrameioUI
  File "C:/Users/justin.li/.nuke\Python\Startup\frameio_exporter\ui\FnFrameioUI.py", line 7, in <module>
    from PySide2.QtWebKit import QWebView
ImportError: No module named QtWebKit
